### project: Probabilistic ash fall hazard assessment to coral reefs in the Coral Triangle
### Jan-Christopher Fischer (jc.fischer@bristol.ac.uk)
### readme - input data

### AOI: Coral Triangle Initiative implementation zone including Singapore and Exclusive Economic Zones of Northern Mariana Islands and Guam
# Exclusive Economic Zones of Northern Mariana Islands and Guam were included because of good past and recent documentation of ash fall impacts on coral reef benthic and reef fish communities (Eldredge, 1982; Eldredge & Kropp; Vroom & Zgliczynski, 2011). 

# Coral Triangle Initiative (CTI) implementation zone:
# file "cti_cff_implementation_area.shp" was downloaded from http://ctatlas.coraltriangleinitiative.org/Dataset on 03.09.2021
# info: The Coral Triangle Initiative on Coral Reefs, Fisheries, and Food Security (CTI-CFF), multilateral partnership of Indonesia, Malaysia, Philippines, Papua New Guinea, Solomon Islands, Timor-Leste with the aim of sustainable use of natural marine and coastal resources. Key topics are food security, climate change, and marine biodiversity.

# EEZ data 
# file "eez_boundaries_v11.shp" Download from https://www.marineregions.org/downloads.php on 03.09.2021 
# Flanders Marine Institute (2019). Maritime Boundaries Geodatabase: Maritime Boundaries and Exclusive Economic Zones (200NM), version 11. Available online at https://www.marineregions.org/. https://doi.org/10.14284/386

# Processing in ArcMap: EEZ of Northern Mariana Islands, Guam and Singapore were combined with CTI zone
# Geoprocessing - Union
# Geoprocessing - Dissolve
# resultant file "AOI.shp" was saved
# 500 km buffer zone around AOI was generated by Geoprocessing - Buffer set linear unit to 500 km
# resultant file "AOI_buff_500_km.shp" was saved


### MPAs
# MPA data download for Guam, Indonesia, Malaysia, Northern Mariana Islands, Papua New Guinea, Philippines, Singapore, Solomon Islands, Timor-Leste from www.protectedplanet.net on 06.09.2021
# UNEP-WCMC and IUCN (2021), Protected Planet: The World Database on Protected Areas (WDPA) and World Database on Other Effective Area-based Conservation Measures (WD-OECM) [Online], September 2021, Cambridge, UK: UNEP-WCMC and IUCN. Available at: www.protectedplanet.net.

### land
# file "ne_10m_land.shp" was downloaded here file:///C:/Users/zs20225/OneDrive%20-%20University%20of%20Bristol/Documents/4D-REEF%20PhD%20Uni%20Bristol/Research/TephraProb%20modelling/Data/Original%20data/ne_10m_land/ne_10m_land.README.html on 14.04.2021

# Processing:
# out of 9 country-specific folders "WDPA_WDOECM_Aug2021_Public_COUNTRY_shp", all "WDPA_WDOECM_Aug2021_Public_COUNTRY_shp-polygons.shp" files were load in ArcMap
# Geoprocessing - Union
# Geoprocessing - Dissolve
# resultant file "WDPA_WDOECM_Sep2021_AOI_all.shp" was saved
# file "WDPA_WDOECM_Sep2021_AOI_all.shp" was cropped: in ArcMap: ArcToolbox - Analysis Tools - Overlay - Erase: Input Features were "WDPA_WDOECM_Sep2021_AOI_all.shp" and Erase Features were "ne_10m_land.shp"
# resultant file "WDPA_WDOECM_Sep2021_AOI_marine.shp" was saved
