#!/bin/bash

#SBATCH --job-name du
#SBATCH --cpus-per-task 1
#SBATCH --time 01:0:00
#SBATCH --partition test
#SBATCH --output du.out

cd $SLURM_SUBMIT_DIR

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

start=`date +%s`

du -h

echo Time is `date`

end=`date +%s`

runtime=`echo "$end - $start" |bc`

function show_time () {
  num=$1
  min=0
  hour=0
  day=0
  sec=0
  if((num>59));then
    ((sec=num%60))
    ((num=num/60))
    if((num>59));then
      ((min=num%60))
      ((num=num/60))
      if((num>23));then
        ((hour=num%24))
        ((day=num/24))
      else
        ((hour=num))
      fi
    else
      ((min=num))
    fi
  else
    ((sec=num))
  fi
  echo "$day"d "$hour"h "$min"m "$sec"s
}

show_time $runtime
