#!/bin/bash

#PBS -N t2_runner
#PBS -l nodes=2:ppn=28
#PBS -l walltime=24:00:00
#PBS -o t2_runner.out

# Update as necessary to run tephra2 & MPI
module load languages/gcc/9.3.0
module load gc/7.4.4-foss-2016a
module load languages/intel/2020-u4
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so

cd $PBS_O_WORKDIR

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $PBS_JOBID
echo This job runs on the following machines:
echo `echo $PBS_NODEFILE | uniq`

start=`date +%s`

mpiexec -n 56 ./t2_runner

echo Time is `date`


end=`date +%s`

runtime=`echo "$end - $start" |bc`

function show_time () {
  num=$1
  min=0
  hour=0
  day=0
  sec=0
  if((num>59));then
    ((sec=num%60))
    ((num=num/60))
    if((num>59));then
      ((min=num%60))
      ((num=num/60))
      if((num>23));then
        ((hour=num%24))
        ((day=num/24))
      else
        ((hour=num))
      fi
    else
      ((min=num))
    fi
  else
    ((sec=num))
  fi
  echo "$day"d "$hour"h "$min"m "$sec"s
}

